circleci-image: &circleci-image
  - image: fr123k/circleci-golang:latest

environment: &environment
  DOCKER_BUILDKIT: 1
  DOCKER_BUILD_CLI_ARGS: --progress=plain

version: 2.1
commands:
  build:
    steps:
      - run:
          name: build image
          command: |
            make docker-build
            ls -lha ~/.cache/go-build || true
            ls -lha "/go/pkg/mod" || true
            go env

  push-images:
    steps:
      - run:
          name: push image to dockerhub
          command: |
            echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_USER} --password-stdin
            make docker-push
jobs:
  build:
    docker: *circleci-image
    resource_class: small
    environment: *environment
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - build
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - when:
          condition:
            and:
              - equal: ["fr/add_circleci", << pipeline.git.branch >>]
          steps:
            - push-images

workflows:
  build:
    jobs:
      - build
