apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-ssm-operator
  namespace: aws-ssm
  annotations:
    # Substitute your account ID and IAM service role name below.
    eks.amazonaws.com/role-arn: arn:aws:iam::350453082100:role/aws-ssm-operator-aws-ssm-role
