apiVersion: ssm.aws/v1alpha1
kind: ParameterStore
metadata:
  name: foo-app
spec:
  valueFrom:
    parametersStoreRef:
    - key: /aurora/mysql/stg/dbpassword
      name: DB_PASSWORD
    - key: /aurora/mysql/stg/dbuser
      name: DB_USER
